"""Dodanie obsługi zleceń - ver 1.5

Revision ID: 4203d612f470
Revises: 04b956d4d1d2
Create Date: 2024-12-04 16:37:20.833089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4203d612f470'
down_revision = '04b956d4d1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_order', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
